apiVersion: v1
kind: PersistentVolume
metadata:
  name: hono-registry-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 128Mi
  hostPath:
    path: /path/to/my/pv # replace with your local directory
  persistentVolumeReclaimPolicy: Recycle
    