kind: PersistentVolume
apiVersion: v1
metadata:
  name: influxdb-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /exports/hono/influxdb         # NFS export name
    server: nfs-server.internal   # IP/hostname address of NFS server
    readOnly: false
